//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevHome.PI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeConHost {
            get {
                return ((bool)(this["IsProcessFilterIncludeConHost"]));
            }
            set {
                this["IsProcessFilterIncludeConHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeDllHost {
            get {
                return ((bool)(this["IsProcessFilterIncludeDllHost"]));
            }
            set {
                this["IsProcessFilterIncludeDllHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeSvcHost {
            get {
                return ((bool)(this["IsProcessFilterIncludeSvcHost"]));
            }
            set {
                this["IsProcessFilterIncludeSvcHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeEdge {
            get {
                return ((bool)(this["IsProcessFilterIncludeEdge"]));
            }
            set {
                this["IsProcessFilterIncludeEdge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeWebview {
            get {
                return ((bool)(this["IsProcessFilterIncludeWebview"]));
            }
            set {
                this["IsProcessFilterIncludeWebview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeRtb {
            get {
                return ((bool)(this["IsProcessFilterIncludeRtb"]));
            }
            set {
                this["IsProcessFilterIncludeRtb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeWmi {
            get {
                return ((bool)(this["IsProcessFilterIncludeWmi"]));
            }
            set {
                this["IsProcessFilterIncludeWmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeWudf {
            get {
                return ((bool)(this["IsProcessFilterIncludeWudf"]));
            }
            set {
                this["IsProcessFilterIncludeWudf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProcessFilterIncludeBgTaskHost {
            get {
                return ((bool)(this["IsProcessFilterIncludeBgTaskHost"]));
            }
            set {
                this["IsProcessFilterIncludeBgTaskHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>50</string>
  <string>350</string>
  <string>964</string>
  <string>680</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SettingsToolPosition {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SettingsToolPosition"]));
            }
            set {
                this["SettingsToolPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string CurrentTheme {
            get {
                return ((string)(this["CurrentTheme"]));
            }
            set {
                this["CurrentTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsCpuUsageMonitoringEnabled {
            get {
                return ((bool)(this["IsCpuUsageMonitoringEnabled"]));
            }
            set {
                this["IsCpuUsageMonitoringEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsInsightsOnStartupEnabled {
            get {
                return ((bool)(this["IsInsightsOnStartupEnabled"]));
            }
            set {
                this["IsInsightsOnStartupEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>70</string>
  <string>942</string>
  <string>640</string>
  <string>222</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ErrorLookupToolPosition {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ErrorLookupToolPosition"]));
            }
            set {
                this["ErrorLookupToolPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsClipboardMonitoringEnabled {
            get {
                return ((bool)(this["IsClipboardMonitoringEnabled"]));
            }
            set {
                this["IsClipboardMonitoringEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>DevHome.PI</string>\r\n  <string>DevEnv</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExcludedProcesses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExcludedProcesses"]));
            }
            set {
                this["ExcludedProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ExpandedLargeSize {
            get {
                return ((global::System.Drawing.Size)(this["ExpandedLargeSize"]));
            }
            set {
                this["ExpandedLargeSize"] = value;
            }
        }
    }
}
