namespace Microsoft.Windows.DevHome.SDK
{
    [version(1.0)]
    interface IPluginAdaptiveCardController 
    {
        void Initialize(IPluginAdaptiveCard pluginUI);
        void Dispose();
        void OnAction(String action, String inputs);
    };

    [version(1.0)]
    interface IPluginAdaptiveCard
    {
        String Template { get; };
        String Data { get; };
        String State { get; };

        void Update(String template, String data, String state);
    };
}