name: "Suggest a new setting/feature within Windows Customization"
description: Suggest a new feature or improvement within Windows Customization (this does not mean you have to implement
  it)
labels:
- Issue-Feature
- Area-Windows-Customization
body:
- id: minwindowsversion
  type: input
  attributes:
    label: Minimum Supported Windows Version
    placeholder: "10.0.23400.0"
    description: What is the minimum version of Windows that should support this feature?
  validations:
    required: true

- id: maxwindowsversion 
  type: input 
  attributes: 
    label: Maximum Supported Windows Version 
    placeholder: What is the maximum version of Windows that should support this feature? If there is no maximum, please enter "None". 
  validations:
    required: true

- id: registrykeys
  type: textarea
  attributes:
    label: Registry Keys
    placeholder: What registry keys are needed to enable this feature? Please provide the full path and value. If not applicable, please enter "None".
  validations:
    required: true 

- id: ispublic
  type: dropdown
  attributes:
    label: Is this feature publicly documented?
    options:
      - Yes
      - No
    description: Is this feature publicly documented? Is there a public API or documentation available?
  validations:
    required: true

- id: publicdocumentation
  type: input
  attributes:
    label: Public Documentation
    placeholder: If there is public documentation for this feature, please provide the link here. If not applicable, please enter "None".
  validations:
    required: true 
    
- id: scenario
  type: textarea
  attributes:
    label: Scenario
    placeholder: How could this new feature be used? Feel free to provide examples.
  validations:
    required: true

- id: supportinginfo
  type: textarea
  attributes:
    label: Additional details
    placeholder: Enter more info or links to give us more details. 
  validations:
    required: false

- type: markdown
  attributes:
    value: Please limit one request per issue.