//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DevHome.Stub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stubs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stubs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DevHome.Stub.Properties.Stubs", typeof(Stubs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying updates… {0}%.
        /// </summary>
        public static string ApplyingUpdates {
            get {
                return ResourceManager.GetString("ApplyingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        public static string Close_window {
            get {
                return ResourceManager.GetString("Close_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading updates… {0}%.
        /// </summary>
        public static string DownloadingUpdates {
            get {
                return ResourceManager.GetString("DownloadingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your system administrator. [Learn more].
        /// </summary>
        public static string ErrorGroupPolicyDetail {
            get {
                return ResourceManager.GetString("ErrorGroupPolicyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App update policies on this PC are preventing you from receiving a required app update..
        /// </summary>
        public static string ErrorGroupPolicyHeader {
            get {
                return ResourceManager.GetString("ErrorGroupPolicyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs an update, but we&apos;re unable to apply the update right now..
        /// </summary>
        public static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connecting? Check [Network &amp; Internet] settings..
        /// </summary>
        public static string ErrorNoNetworkDetail {
            get {
                return ResourceManager.GetString("ErrorNoNetworkDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the Internet and try again.
        /// </summary>
        public static string ErrorNoNetworkHeader {
            get {
                return ResourceManager.GetString("ErrorNoNetworkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Submit feedback], and we’ll look into this as soon as we can..
        /// </summary>
        public static string ErrorOtherDetail {
            get {
                return ResourceManager.GetString("ErrorOtherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still need help? Let us know!.
        /// </summary>
        public static string ErrorOtherHeader {
            get {
                return ResourceManager.GetString("ErrorOtherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs an update. We are getting the update ready for you….
        /// </summary>
        public static string InfoHeader {
            get {
                return ResourceManager.GetString("InfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install {0}.
        /// </summary>
        public static string InstallButtonLabel {
            get {
                return ResourceManager.GetString("InstallButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing {0} for first launch….
        /// </summary>
        public static string PreparingForFirstLaunch {
            get {
                return ResourceManager.GetString("PreparingForFirstLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to install.
        /// </summary>
        public static string ProgressReadyText {
            get {
                return ResourceManager.GetString("ProgressReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgainButtonLabel {
            get {
                return ResourceManager.GetString("TryAgainButtonLabel", resourceCulture);
            }
        }
    }
}
